on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Install additional LaTeX packages
        run: |
          tlmgr update --all --self
          tlmgr install eurosym \
                        adjustbox \
                        caption \
                        collectbox \
                        enumitem \
                        environ \
                        fp \
                        jknapltx \
                        ms \
                        parskip \
                        pgf \
                        rsfs \
                        tcolorbox \
                        titling \
                        trimspaces \
                        ucs \
                        ulem \
                        upquote \
                        collection-fontsrecommended \
                        tcolorbox \
                        mathpazo
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libpng-dev \
            libjpeg-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libtiff5-dev
      
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}